version: '3'
services:
  box1:
    build:
      context: .
      dockerfile: docker/Dockerfile-server1
    ports:
      - "2020:22"
  http:
    build:
      context: .
      dockerfile: docker/Dockerfile-caddy
    restart_policy:
      condition: unless-stopped
      delay: 5s
      max_attempts: 2
      window: 7200s
    ports:
      - 2015:2015
      - 80:80
      - 443:443
      
