FROM alpine

RUN apk add --update --no-cache \
    bash \
    curl

RUN curl https://getcaddy.com | bash -s personal http.cors

WORKDIR /caddy

COPY ./docker/Caddyfile /caddy

EXPOSE 80 443 2015

CMD [ "caddy" ]
