FROM ubuntu:latest

# Set the basic stuff, like hostname
RUN echo JayServer1 > /etc/hostname

# Setup the SSH
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd && chmod 0755 /var/run/sshd && /usr/sbin/sshd

# Copy passwords
COPY ./servers/server1/passwords /root/passwords
COPY ./servers/server1/JayServer1.sh /root/JayServer1.sh
RUN /root/JayServer1.sh

# Start the zombie mode, so it's accessible and doesn't return
COPY ./starter.sh /root/starter.sh
CMD ["/root/starter.sh"]